name: First Workflow

on:
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Step 1 complete!"
      - name: Step 2
        run: echo "Step 2 complete!"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Cowsays Action
        uses: peter-evans/cowsay-action@v1
        with:
          text: "Ready for prod–ship it!"
          color: magenta